[versions]

# Gradle plugins
gradlePlugins-detekt = "1.23.4"
kotlin-core = "2.0.0-Beta3"

# Logging
logging-log4j = "2.22.1"


# Testing
mockk = "1.13.9"

[libraries]

# Gradle plugins
gradlePlugins-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradlePlugins-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "gradlePlugins-detekt" }

# Checkstyle
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "gradlePlugins-detekt" }

# Logging
logging-log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "logging-log4j" }
logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "logging-log4j" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
