[versions]

# Kotlin
kotlin-core = "2.0.0-Beta1"

# Compose
jb-compose = "1.6.0-rc01"

# Gradle plugins
gradlePlugins-android = "8.2.2"
gradlePlugins-detekt = "1.23.4"
gradlePlugins-modulesGraphAssert = "2.5.0"

# Android
android-activity-compose = "1.8.2"

# Logging
logging-log4j = "2.22.1"

# Testing
mockk = "1.13.9"

[libraries]

# Gradle plugins
gradlePlugins-kotlin-core = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-core" }
gradlePlugins-jb-compose = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "jb-compose" }
gradlePlugins-android = { module = "com.android.tools.build:gradle", version.ref = "gradlePlugins-android" }
gradlePlugins-detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "gradlePlugins-detekt" }
gradlePlugins-modulesGraphAssert = { module = "com.jraska.module.graph.assertion:plugin", version.ref = "gradlePlugins-modulesGraphAssert" }

# Android
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "android-activity-compose" }

# Checkstyle
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "gradlePlugins-detekt" }

# Logging
logging-log4j-api = { module = "org.apache.logging.log4j:log4j-api", version.ref = "logging-log4j" }
logging-log4j-core = { module = "org.apache.logging.log4j:log4j-core", version.ref = "logging-log4j" }

# Testing
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
