# Usage:
# - name: Setup java
#   uses: ./.github/actions/setup_java

name: setup_java
description: Setup java && gradle cache
runs:
  using: composite
  steps:
    - uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 21
        cache: gradle
