# Usage:
# - name: Gradle cache
#   uses: ./.github/actions/gradle_cache

name: gradle_cache
description: Gradle gradle
inputs:
  key:
    required: true
    description: primary cache key
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.gradle
        key: ${{ inputs.key }}-${{ runner.os }}-${{ github.sha }}
        restore-keys: |
          ${{ inputs.key }}-${{ runner.os }}-
