# Usage:
# - name: Gradle cache
#   uses: ./.github/actions/gradle_cache

name: gradle_cache
description: Gradle gradle
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-${{ hashFiles('~/.gradle/**') }}
