name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-gradle-modules-graph:
    name: Check gradle modules graph
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Gradle cache
        uses: ./.github/actions/gradle_cache
        with:
          key: "check_gradle_modules_graph"

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: :assertModuleGraph

  check-detekt:
    name: Check detekt
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Gradle cache
        uses: ./.github/actions/gradle_cache
        with:
          key: "check_detekt"

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: >-
            :detektBuildLogic
            detekt  

  assemble-android-debug-client:
    name: Assemble android debug client
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Gradle cache
        uses: ./.github/actions/gradle_cache
        with:
          key: "assemble_android_debug_client"

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: :client:assembleDebug

# MaсOs сборки слишком долгие
#  assemble-macos-client:
#    name: Assemble macos client
#    runs-on: macos-14
#    timeout-minutes: 30
#    steps:
#      - name: Clone repository
#        uses: actions/checkout@v4
#
#      - name: Setup java
#        uses: ./.github/actions/setup_java
#
#      - name: Gradle cache
#        uses: ./.github/actions/gradle_cache
#        with:
#          key: "assemble_macos_client"
#
#      - name: Run gradle
#        uses: ./.github/actions/run_gradle
#        with:
#          gradle_command: >-
#            :client:macosArm64Binaries

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Gradle cache
        uses: ./.github/actions/gradle_cache
        with:
          key: "unit_tests"

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          # allTest (not working by wasm target)
          gradle_command: >-
            jvmTest
            jsTest
            testDebugUnitTest
