name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-gradle-modules-graph:
    name: Check gradle modules graph
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: :assertModuleGraph

  check-detekt:
    name: Check detekt
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: >-
            :detektBuildLogic
            detekt  

  assemble-android-debug-client:
    name: Assemble android debug client
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: :client:android:assembleDebug

  assemble-macos-client:
    name: Assemble macos client
    runs-on: macos-14
    timeout-minutes: 30
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: >-
            :client:macos:macosArm64Binaries
            :client:macos:macosX64Binaries

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: allTests
