name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-detekt:
    name: Check detekt
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: >-
            :detektBuildLogic
            detekt

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Setup java
        uses: ./.github/actions/setup_java

      - name: Run gradle
        uses: ./.github/actions/run_gradle
        with:
          gradle_command: allTests
