name: CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Run gradle
        run: >-
          ./gradlew
          :ci
          --no-daemon
          --stacktrace
