name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check-gradle-modules-graph:
    name: Check gradle modules graph
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Run gradle
        uses: ./vs-control/.github/actions/run_gradle_default
        with:
          key: "check_gradle_modules_graph"
          gradle_command: :assertModuleGraph

  check-detekt:
    name: Check detekt
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Run gradle
        uses: ./vs-control/.github/actions/run_gradle_default
        with:
          key: "check_detekt"
          gradle_command: >-
            :detektBuildLogic
            detekt  

  assemble-android-debug-client:
    name: Assemble android debug client
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Run gradle
        uses: ./vs-control/.github/actions/run_gradle_default
        with:
          key: "assemble_android_debug_client"
          gradle_command: :client:assembleDebug

  assemble-jvm-client:
    name: Assemble jvm client
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Run gradle
        uses: ./vs-control/.github/actions/run_gradle_default
        with:
          key: "assemble_jvm_client"
          gradle_command: :client:jvmJar

  unit-tests:
    name: Unit tests
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - name: Run gradle
        uses: ./vs-control/.github/actions/run_gradle_default
        with:
          key: "unit_tests"
          # allTest (not working by wasm target)
          gradle_command: >-
            jvmTest
            testDebugUnitTest
